### ISSUE TITLE
Unable to install Azure SQL Migration Extension in Azure Data Studio due to version incompatibility

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/TechExcel-Securely-migrate-Windows-Server-and-SQL-Server-workloads-to-Azure#3]
Problem:
The version of Azure Data Studio that's installed on the onprem-sql-vm is incompatible with the latest version of the Azure SQL Migration Extension, and will not allow it to be installed.

Fix:
Update the ARM Template that deploys the onprem-sql-vm so that it has Azure Data Studio v1.46.1 installed.
https://github.com/microsoft/azuredatastudio/releases/tag/1.46.1

The reason for this is that the VM is on Windows Server 2012 R2 which is incompatible with the latest version of Azure Data Studio. Also, the marketplace image used to provision the VM has Azure Data Studio 1.37.0 which is incompatible with the latest version of the Azure SQL Migration Extension.

Alternative Fix:
Update the lab environment to use Windows Server 2016 that is compatible with the latest version of Azure Data Studio.

**Comment by tiagocostapt** [comment]
Solution steps have been updated to fix this.
