### ISSUE TITLE
Bicep template missing Hub-Spoke VNet 2-way Peering

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/TechExcel-Securely-migrate-Windows-Server-and-SQL-Server-workloads-to-Azure#5]
Problem:
The Bicep template is missing a Peering from the Hub VNet to the Spoke VNet.
There's a Spoke to Hub, but not Hub to Spoke. Peering needs to be 2 way for it to work.

Workaround until Bicep is fixed:
Go to the Spoke VNet, delete the spoke-hub peering that's there, and create a new one with the following config. After this the Bastion connection will work to connect to the `webapp-vm` that's created in the lab.

<img width="811" alt="image" src="https://github.com/microsoft/TechExcel-Securely-migrate-Windows-Server-and-SQL-Server-workloads-to-Azure/assets/392297/6ef739e8-7b1c-492e-9010-f445885a75d0">

**Comment by tiagocostapt** [comment]
This was taken care. Thanks for the report.
