### ISSUE TITLE
Ex 4 Task 5: "Solution" steps appear to be incomplete

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/TechExcel-Securely-migrate-Windows-Server-and-SQL-Server-workloads-to-Azure#6]
The "Solution" steps defined to walk through setting up the Azure Firewall appear to be incomplete. They create the Azure Firewall, but do not walk through the steps to configure the Firewall to block access to "bing.com" and test network traffic from the VM.

**Comment by tiagocostapt** [comment]
Fixed.
