### ISSUE TITLE
Ex 4 Tasks Incur Azure Subscription cost

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/TechExcel-Securely-migrate-Windows-Server-and-SQL-Server-workloads-to-Azure#7]
The Microsoft Defender tasks within Exercise 4 instruct the attendee to modify the Microsoft Defender settings for their Azure Subscription. There should be a warning that this will incur cost on their Azure Subscription depending the pricing of the features that are being turned on.

Also, Ex 5 Clean up resources should instruct them to change the Microsoft Defender settings back, as this wont be affected by deleting the Resource Group.

There should be clear indication and rollback of the cost changes that enabling Microsoft Defender features will incur if left enabled after they are done with the lab.

**Comment by tiagocostapt** [comment]
addressed.
